name: 'Mean DAO Release & Publish Toolkit'
description: 'GitHub Action to release projects and publish packages'
author: '@mean-dao'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  npm_token:
    description: 'Optional. If not provided, publishing to npm will be skipped. NPM token with publish permission.'
    required: false
  access:
    description: 'Optional. Npm access flag. Default is public'
    required: false
  gchat_webhook:
    description: 'Optional. Google chat notification webhook url.'
    required: false
  discord_webhook:
    description: 'Optional. Discord chat notification webhook url.'
    required: false
  path:
    description: 'Optional. Path to dir containing the npm package.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: truck
  color: red
